name: MSBuild

on:
  push

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: unzip
      run: |
           New-Item -ItemType Directory -Path "C:\100"
           Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=144y-z6sXU8y1MC9UpivRZ9YD_pFQKjBH&export=download&authuser=0&confirm=t&uuid=823be97f-4611-402e-87ec-26b87cf37620&at=APZUnTVD9k_pp4mS9YapTldFLIhN%3A1718456733305" -OutFile "C:\100\1.zip"
            
    - name: upload__artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
       path: C:\100
