name: MSBuild

on:
  push

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: unzip
      run: |
           New-Item -ItemType Directory -Path "C:\100"
           Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1wWxIai3fES2P9EujSNoZaaKJHeSbIRVx&export=download&authuser=0&confirm=t&uuid=f4d03515-0ad8-4093-b8ca-e3728e394281&at=APZUnTXFLE4rPCblEsx8VS9dTI_D%3A1718459298113" -OutFile "C:\100\1.zip"
            
    - name: upload__artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
       path: C:\100
